### ISSUE TITLE
Latest version of geotagger plugin is not working with Recogito 1.4.0

### ISSUE THREAD

**Issue by dpancic** [recogito/geotagger#16]
The command: 

`npm run install-plugin recogito/geotagger `

returns following errors:
> [ERROR] [vite] x Build failed in 3.75s
> Could not resolve "../../../plugins/geotagger/plugin.config.json" from "src/components/Plugins/deployedPlugins.ts"
> file: /recogito-client/src/components/Plugins/deployedPlugins.ts
>   Stack trace:
>     at getRollupError (file:///recogito-client/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
>     at ModuleLoader.handleInvalidResolvedId (file:///recogito-client/node_modules/rollup/dist/es/shared/node-entry.js:20207:24)
> \Starting Client app
> node:internal/modules/cjs/loader:1143
>   throw err;
>   ^
> Error: Cannot find module '/recogito-client/dist/server/entry.mjs'
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
>     at Module._load (node:internal/modules/cjs/loader:981:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
>     at node:internal/main/run_main_module:28:49 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }

After downgrading to the commit: 

`npm install git+https://github.com/recogito/geotagger.git#933b579`

Installing works again, but plugin cannot be found over the Recogito GUI and cannot be used.
Is there a release of this plugin that can work with Recogito 1.4.0?

**Comment by dpancic** [comment]
The problem is solved by cloning version 0.1 into the plugins directory:

`git clone --branch v0.1 https://github.com/recogito/geotagger.git /recogito-client/plugins/geotagger`
